classDiagram
	%% the '$' symbol represents a static property/method

	class Driver {
		-string name
		-bool isInCar
		-startCar()
		-stopCar()
	}

	class Car {
		+array listOfComponents$
		+string colour
		+string bodyType
		+string fuelType
		+number numberOfDoors
		+object dimensions
		-string VIN
		
		+unlock()
		+lock()
		+drive(destination)
		+stop()
	}

	class SteeringWheel {
		+string material
		+string shape
		+number diameter
		+rotate(angle)
	}

	class WindshieldWiper {
		+number count$
		+string material
	}

	class Horn {
		+Audio sound
	}

	class Tyre {
		+number count$
		+string material
		+string dimensionsCode
	}

	class Engine {
		-float engineSize
		-number cylinders
		-bool engineOn
		-toggleEngine()
	}

	class Door {
		+number count$
	}
	



	Driver "1" o.. "many" Car : aggregation
	Car *.. SteeringWheel : composition
	Car *.. Tyre : composition
	Car *.. Engine : composition
	Car *.. WindshieldWiper : composition
	Car *.. Door : composition

	SteeringWheel "1" *.. "1" Horn